### ISSUE TITLE
python scripts do not work with new library numpy and tensorflow

### ISSUE THREAD

**Issue by fabiovito** [jonathanmarek1/binarynet-tensorflow#3]
Thanks for your paper. I think it's very usefull for embedded application.
But your python scripts do not work with new library version numpy and tensorflow.
below an example:
fabio@fabio-VirtualBox:~/binarynet-tensorflow/binarynet-tensorflow(master)> python xnornet.py 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "xnornet.py", line 13, in <module>
    import bnn
  File "/home/fabio/binarynet-tensorflow/binarynet-tensorflow/bnn.py", line 47
    x = tf.nn.conv2d(x, W, strides=[1, *stride, 1], padding=padding) + b
                                       ^
SyntaxError: invalid syntax

fabio@fabio-VirtualBox:~/binarynet-tensorflow/binarynet-tensorflow(master)> python benchmark.py 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "benchmark.py", line 2, in <module>
    import bnn
  File "/home/fabio/binarynet-tensorflow/binarynet-tensorflow/bnn.py", line 47
    x = tf.nn.conv2d(x, W, strides=[1, *stride, 1], padding=padding) + b
                                       ^
SyntaxError: invalid syntax

fabio@fabio-VirtualBox:~/binarynet-tensorflow/binarynet-tensorflow(master)> python cifar_bnn.py 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "cifar_bnn.py", line 6, in <module>
    import bnn
  File "/home/fabio/binarynet-tensorflow/binarynet-tensorflow/bnn.py", line 47
    x = tf.nn.conv2d(x, W, strides=[1, *stride, 1], padding=padding) + b
                                       ^
SyntaxError: invalid syntax

This is my pip library tools:
fabio@fabio-VirtualBox:~/binarynet-tensorflow/binarynet-tensorflow(master)> pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
absl-py (0.1.7)
acoustics (0.1.2)
adium-theme-ubuntu (0.3.4)
alabaster (0.7.7)
appnope (0.1.0)
asn1crypto (0.24.0)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0.post1)
bleach (1.5.0)
ccsm (0.9.12.2)
certifi (2017.11.5)
cffi (1.11.2)
chainer (2.0.1)
chardet (3.0.4)
compizconfig-python (0.9.12.2)
cryptography (2.1.4)
cupy (1.0.3)
cycler (0.9.0)
Cython (0.27.3)
decorator (4.0.10)
deepx (0.3.20)
docutils (0.12)
dot2tex (2.9.0)
enum34 (1.1.6)
filelock (2.0.13)
funcsigs (1.0.2)
futures (3.2.0)
h5py (2.7.1)
html5lib (0.9999999)
idna (2.6)
imagesize (0.7.1)
ipaddress (1.0.19)
ipython (5.0.0)
ipython-genutils (0.1.0)
Jinja2 (2.8)
joblib (0.9.4)
leveldb (0.1)
lmdb (0.86)
Markdown (2.6.11)
MarkupSafe (0.23)
matplotlib (1.5.1)
meld (3.14.2)
mock (2.0.0)
ndg-httpsclient (0.4.3)
nose (1.3.7)
numpy (1.14.0)
olefile (0.44)
pandas (0.22.0)
pathlib2 (2.1.0)
pbr (3.1.1)
pexpect (4.2.0)
pickleshare (0.7.3)
Pillow (4.3.0)
pip (9.0.1)
prompt-toolkit (1.0.5)
protobuf (3.5.1)
ptyprocess (0.5.1)
pyasn1 (0.4.2)
pycparser (2.18)
pycurl (7.43.0)
Pygments (2.1.3)
pygobject (3.20.0)
pyOpenSSL (17.5.0)
pyparsing (2.0.3)
Pyste (0.9.10)
python-apt (1.1.0b1)
python-dateutil (2.4.2)
python-speech-features (0.6)
pytz (2016.6.1)
PyYAML (3.11)
requests (2.18.4)
roman (2.0.0)
scikit-learn (0.19.1)
scipy (0.17.0)
setuptools (38.4.0)
simplegeneric (0.8.1)
simplejson (3.8.1)
six (1.11.0)
snowballstemmer (1.2.1)
solar-theme (1.3.2)
Sphinx (1.4.5)
sphinx-rtd-theme (0.1.9)
tabulate (0.8.2)
tensorflow (1.4.1)
tensorflow-tensorboard (0.4.0rc3)
Theano (1.0.0+28.g55e94968f, /home/fabio/theano/Theano)
torch (0.3.0.post4)
torchvision (0.2.0)
traitlets (4.2.2)
unity-lens-photos (1.0)
urllib3 (1.22)
vboxapi (1.0)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.30.0)
xdot (0.6)

**Comment by wjtan99** [comment]
@jonathanmarek1 I used python 3.4 but it still says 

Traceback (most recent call last):
  File "cifar_bnn.py", line 6, in <module>
    import bnn
  File "/media/ubuntu/data/opensource/binarynet-tensorflow/bnn.py", line 47
    x = tf.nn.conv2d(x, W, strides=[1, *stride, 1], padding=padding) + b
                                          ^
SyntaxError: can use starred expression only as assignment target

what python version and tensorflow do you use?  
Thanks.

**Comment by wjtan99** [comment]
I retried python 3.5, tensorflow_gpu 1.4.1 and it worked.
